name: Deploy to gh-pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Commit and push changes
        run: |
          run: cp -r master/_book/* gh-pages/
          git add .
          git commit -m "Auto-deploy to gh_pages"
          git push
