name: Deploy to gh-pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Commit and push changes
        run: |
          mkdir -p deploy
          cp -r _book/* deploy/
          git checkout gh-pages
          cp -r deploy/* .
          rm -rf deploy
          git add .
          git commit -m "Auto-deploy to gh_pages"
          git push origin gh-pages
